<?php

/**
 * @file
 * Contains generic functions.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;
use Drupal\views\ViewExecutable;
use Drupal\webform\Entity\WebformSubmission;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_help().
 */
function custom_booking_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.custom_booking':

      return '<p>' . t('A custom module to handle a booking alterations.') . '</p>';

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function custom_booking_form_alter(&$form, &$form_state, $form_id) {
  // Weform form alter.
  if ($form_id == 'webform_submission_create_booking_add_form' || $form_id == 'webform_submission_create_booking_edit_form') {
    // Add wrapper to ajax call.
    $form['elements']['booking_details']['assign_room']['#prefix'] = '<div id="ajax-wrapper-field-offices">';
    $form['elements']['booking_details']['assign_room']['#suffix'] = '</div>';
    // Ajax call.
    $form['elements']['booking_details']['guesthouse']['#ajax'] = [
      'event' => 'change',
      'callback' => 'custom_booking_update_room_list_callback',
      'wrapper' => 'ajax-wrapper-field-offices',
    ];
    $guesthouseId = $form_state->getValue('guesthouse');
    if (!empty($guesthouseId)) {
      $commonService = \Drupal::service('common_services');
      $guesthouseId = $form_state->getValue('guesthouse');
      $startDate = $form_state->getValue('start_date');
      $endDate = $form_state->getValue('end_date');
      $options = $commonService->getRoomListOptions($guesthouseId, $startDate, $endDate);
      $form['elements']['booking_details']['assign_room']['#options'] = $options;

      // Added js and css for webform.
      $form['#attached']['library'][] = 'custom_booking/global-library';
    }
  }
  // Called custom validation.
  $form['#validate'][] = 'custom_booking_webform_custom_booking_validation';
}

/**
 * Implements hook_views_exposed_form_alter().
 */
function custom_booking_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form["#id"] == 'views-exposed-form-room-availability-page-1') {
    // Added start and end date filter.
    $form['start_date'] = [
      '#type' => 'date',
      '#title' => t('Start Date'),
    ];
    $form['end_date'] = [
      '#type' => 'date',
      '#title' => t('End Date'),
    ];
  }
}

/**
 * Implements hook_views_pre_render().
 */
function custom_booking_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'room_availability') {
    $view->element['#attached']['library'][] = 'custom_booking/global-library';
  }
}

/**
 * Implements hook_views_data().
 */
function custom_booking_views_data() {
  $data['views']['table']['group'] = t('Custom Global');
  $data['views']['table']['join'] = [
    // #global is a special flag which allows a table to appear all the time.
    '#global' => [],
  ];

  $data['views']['available_rooms'] = [
    'title' => t('Available rooms'),
    'help' => t('Show available room remaning capacity.'),
    'field' => [
      'id' => 'available_rooms',
    ],
  ];
  return $data;
}

/**
 * Ajax callback function.
 */
function custom_booking_update_room_list_callback(array &$form, FormStateInterface $form_state) {
  $commonService = \Drupal::service('common_services');
  $guesthouseId = $form_state->getValue('guesthouse');
  $startDate = $form_state->getValue('start_date');
  $endDate = $form_state->getValue('end_date');
  $options = $commonService->getRoomListOptions($guesthouseId, $startDate, $endDate);
  // Add dynamic options to assign room field.
  $form['elements']['booking_details']['assign_room']['#options'] = $options;
  $field_room_element = \Drupal::service('renderer')->render($form['elements']['booking_details']['assign_room']);

  // Return the HTML of the updated element as the AJAX response.
  $response = new AjaxResponse();
  $response->addCommand(new HtmlCommand('#ajax-wrapper-field-offices', $field_room_element));

  return $response;
}

/**
 * Implements hook_webform_submission_presave().
 */
function custom_booking_webform_submission_presave(WebformSubmissionInterface $webform_submission) {
  $commonService = \Drupal::service('common_services');
  $employeeStatus = $webform_submission->getElementData('employee_status');
  $emp = $webform_submission->getElementData('select_employee');
  $isChargable = $webform_submission->getElementData('is_chargeable');
  // Add exisiting employee name and email in field.
  if ($employeeStatus == 'old' && !empty($emp)) {
    $user = User::load($emp);
    $email = $user->get('mail')->value;
    $name = $user->get('name')->value;
    $webform_submission->setElementData('employee_name', $name);
    $webform_submission->setElementData('employee_email', $email);
  }
  // Count total chargs and add it into the total amount field.
  if ($isChargable == 1) {
    $startDate = $webform_submission->getElementData('start_date');
    $endDate = $webform_submission->getElementData('end_date');
    $roomType = $webform_submission->getElementData('room_occupancy');
    $totalDays = $commonService->getTotalDays($startDate, $endDate);
    $charges = $commonService->totalCostCalculation($totalDays, $roomType);
    $webform_submission->setElementData('total_amount', $charges);
  }
  else {
    $webform_submission->setElementData('total_amount', 0);
  }
}

/**
 * Custom booking overlapping validation.
 */
function custom_booking_webform_custom_booking_validation($form, FormStateInterface $form_state) {
  $startDate = $form_state->getValue('start_date');
  $endDate = $form_state->getValue('end_date');
  $guesthouse = $form_state->getValue('guesthouse');
  $roomOccupancy = $form_state->getValue('room_occupancy');
  $roomId = $form_state->getValue('assign_room');
  $commonService = \Drupal::service('common_services');
  // Get the submission ID from the route parameters.
  $submission_id = $commonService->getSubmissionId();
  if ($submission_id instanceof WebformSubmission) {
    $submission_id = $submission_id->id();
  }
  // Ensure that the end date is not before the start date.
  if (!empty($startDate) && !empty($endDate) && strtotime($endDate) < strtotime($startDate)) {
    $form_state->setErrorByName('end_date', t('End date cannot be a past date compared to the start date.'));
  }
  else {
    // Check if there are overlapping bookings.
    if (!empty($guesthouse) && !empty($roomOccupancy) && !empty($roomId)) {
      $bookedRoomNids = $commonService->getBookedNids($startDate, $endDate, $roomId, $guesthouse);
      // For edit form confition.
      if (!empty($submission_id) || $submission_id != '') {
        if (in_array($submission_id, $bookedRoomNids)) {
          $bookedRoomNids = array_diff($bookedRoomNids, [$submission_id]);
        }
      }
      if (count($bookedRoomNids) == 1) {
        $submission = WebformSubmission::load(reset($bookedRoomNids));
        if ($submission) {
          $occupancy = $submission->getElementData('room_occupancy');
        }
      }
      // Load room capacity.
      $roomCapacity = $commonService->getRoomCapacity($roomId);
      // Check for single occupancy.
      if ($roomOccupancy == 'single' && count($bookedRoomNids) >= 1) {
        $form_state->setErrorByName('assign_room', t('The room is fully booked for single occupancy during the selected date range.'));
      }
      elseif ($occupancy == 'single' && $roomOccupancy == 'shared') {
        // If user booked single room in date range,
        // then restrict them to create shared booking.
        $form_state->setErrorByName('assign_room', t('The room is fully booked within the specified date range.'));
      }
      elseif ($roomOccupancy == 'shared' && (count($bookedRoomNids) >= $roomCapacity)) {
        // If room is shared and check room capacity.
        $form_state->setErrorByName('assign_room', t('The room is fully booked within the specified date range.'));
      }
    }
  }
}
